name: CI

on: [push, pull_request_target, workflow_dispatch]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup node & pnpm
        uses: pnpm/setup@v1
        with:
          cache-dependency-path: source/pnpm-lock.yaml
          package-json-file: source/package.json
          run_install: |
            - cwd: source
          cache: true

      - name: Run lint
        working-directory: source
        run: |
          pnpm run lint
      
      - name: Test build
        working-directory: source
        run: |
          pnpm run build